### ISSUE TITLE
Torchaudio & pocketfft 0.10

### ISSUE THREAD

**Issue by StuartIanNaylor** [Qengineering/PyTorch-Raspberry-Pi-64-OS#1]
I think finally Torch & Torch audio can be compiled with alternatives for cpu than intel MKL

I had a go with https://github.com/KumaTea/pytorch-aarch64 but the examples I ran from speechbrain just seem to return null without error.

I was wondering if your planning on providing torchaudio also?

Stuart

**Comment by Qengineering** [comment]
Sorry, not in the near future.

**Comment by StuartIanNaylor** [comment]
No probs I will have a look at see if I can work it out. There is a beta beamformer in there (audio wise) that looks interesting also :)
